version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "devcontainers"
    directory: ".devcontainer"
    schedule:
      interval: "monthly"
